version: "3"

services:
    southbound:
        image: eclipse-mosquitto:1.6.9
        hostname: southbound.mosquitto
        container_name: southbound.mosquitto
        ports: 
            - "1883:1883"
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
        networks:
            default:
                aliases:
                    - southbound.mosquitto
    influxdb:
        image: influxdb:1.7-alpine
        hostname: influxdb.service
        container_name: influxdb.service
        volumes:
            - ./influxdb.conf:/etc/influxdb/influxdb.conf
        networks:
            default:
                aliases:
                    - influxdb.service
        ports:
            - 8086:8086

    mongodb:
        image: mvertes/alpine-mongo:4.0.6-1
        hostname: mongodb.service
        container_name: mongodb.service
        volumes:
            - "./mongodb-data:/data/db"
        ports: 
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
