version: "3.1"
services:

  southbound:
    restart: always
    image: eclipse-mosquitto
    hostname: southbound.mosquitto
    container_name: chariot.southbound.broker
#    expose:
#      - "1883"
#      - "9001"
#    ports:
#      - "1883:1883"
#      - "9001:9001"
    volumes:
      - ./mosquitto/southbound/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      default:
        ipv4_address: 172.18.1.2
        aliases:
          - southbound.mosquitto

  northbound:
    restart: always
    image: eclipse-mosquitto
    hostname: northbound.mosquitto
    container_name: chariot.northbound.broker
#    expose:
#      - "1883"
#      - "9001"
#    ports:
#      - "1883:1883"
#      - "9001:9001"
    volumes:
      - ./mosquitto/northbound/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      default:
        ipv4_address: 172.18.1.3
        aliases:
          - northbound.mosquitto

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
